# Generated by Django 5.2.7 on 2025-10-04 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_user_order_ticket_alter_movie_actors_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='seats',
            new_name='seat',
        ),
    ]
